# Generated by Django 3.2.6 on 2022-03-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('startTime', models.CharField(max_length=200)),
                ('endTime', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='media')),
                ('details', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('udate', models.DateField(blank=True, null=True)),
                ('ustartTime', models.CharField(max_length=200)),
                ('uendTime', models.CharField(max_length=200)),
                ('uprefix', models.CharField(max_length=200)),
                ('ufirstname', models.CharField(max_length=200)),
                ('umiddlename', models.CharField(max_length=200)),
                ('ulastname', models.CharField(max_length=200)),
                ('uage', models.IntegerField()),
                ('ugender', models.CharField(max_length=200)),
                ('uaddress', models.CharField(max_length=200)),
                ('uemail', models.CharField(max_length=200)),
                ('unumber', models.CharField(max_length=200)),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corr.image')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corr.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corr.image'),
        ),
    ]
