# Generated by Django 3.2.6 on 2022-03-16 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='roomName',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corr.image'),
        ),
    ]
