# Generated by Django 4.0.3 on 2022-03-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corr', '0002_auto_20220316_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
